IBM/nodejs-itoolkit

- lib/icmd.js
- lib/iconn.js
- lib/ipgm.js
- lib/iqsh.js
- lib/ish.js
- lib/isql.js
- lib/programCaller.js
- lib/utils.js
Modularize itoolkit.js see issue #20 
- Moved classes and functions into seperate modules
- Added exports to still allow access through itoolkit.js
- iConn class moved to iconn.js
- iPgm class moved to ipgm.js
- iSql class moved to isql.js
- iCmd function moved to icmd.js
- iSh function moved to ish.js
- ProgramCaller moved to programCaller.js
- xmlToJson moved to utils.js
Lint `xmlToJson` function
- Note: 2 lines have ignored lint rules: 146 and 148
> Modularize itoolkit.js see issue #20

- lib/ProgramCall.js
- lib/iconn.js
- lib/idataq.js
- lib/inetwork.js
- lib/iobj.js
- lib/ipgm.js
- lib/iprod.js
- lib/isql.js
- lib/istoredp.js
- lib/itoolkit.js
- lib/iuserSpace.js
- lib/iwork.js
- renamed 'ProgramCaller' to 'ProgramCall' since it doesn't actually call a program, just stores data for the call to the program that is then made by iConn
- Removed all of the 'sync/async' logic. For now, only async with callbacks. Eventually, would be great if we turned these all into promises.
- Further fixing eslint warnings. There is only one that I can't figure out what it wants (iWork, line 68). Also removing `// eslint-disable-line new-cap` throughout (except for dbconn).
> Removing sync, continued linting, renaming classes

- .github/dco.yml
- .npmignore
- CONTRIBUTING.md
- README.md
Adds missing contribution guidelines as well as config for DCO bot.
Along the way:
- updated README to link to contribution guidelines
- .npmignore to ignore .github/ and other files
Once merged I will make a request to setup the DCO bot
> Add contribution guidelines

- lib/ProgramCall.js
- lib/ixml.js
- test/unit/iPgmUnit.js
Performed a `git merge upstream/master` while on `upstream/v1.0-dev` branch.
Had to resolve some conflicts because files where moved around.
> Sync up PR #43 to v1.0-dev after it was merged into master

- lib/Connection.js
- lib/transports/sshTransport.js
- lib/utils.js
- package.json
- test/functional/CommandCallFunctional.js
- test/functional/ProgramCallFunctional.js
- test/functional/SqlCallFunctional.js
- test/functional/ToolkitFunctional.js
Adds new ssh transport see #26 
update package.json 
- include `ssh2` dependency and also adds missing `depd` dependency.
- change version to 1.0.0
- reword description
- bump version of eslint
tests
- [utils.js] add ssh transport to available transports
- update functional tests configurations
TODO:
Document required dependency of `xmlservice-cli` provided by itoolkit-utils package.
`yum install itoolkit-utils`
> Add SSH Transport

- README.md
- lib/Connection.js
- lib/transports/odbcTransport.js
- lib/utils.js
- package.json
- test/functional/CommandCallFunctional.js
- test/functional/ProgramCallFunctional.js
- test/functional/SqlCallFunctional.js
- test/functional/ToolkitFunctional.js
Part of the overall #26 issue.
> Add ODBC Transport

- lib/transports/odbcTransport.js
- package.json
The node-odbc updated the API and connections are no longer obtained through the Connection constructor. Instead a call to the connect function will return a connected Connection object.
> Update odbc transport

- lib/transports/irest.js
- test/functional/ToolkitFunctional.js
- test/functional/deprecated/iProdFunctional.js
> use POST method for rest transports

- lib/transports/odbcTransport.js
Add missing check for connectError in [odbcTransport.js](https://github.com/IBM/nodejs-itoolkit/blob/v1.0-dev/lib/transports/odbcTransport.js#L55) if there was a connect error bail out.
Before adding this check and a connect error occured the following error would be thrown:
```js
connection.query(sql, [ipc, ctl, xmlInput], (queryError, results) => {
^
TypeError: Cannot read property 'query' of null
```
> [odbcTransport.js] Add check for connectError

- package.json
Bump version to release v1.0.0-alpha.1 which adds check for connect error for the odbc transport. See [commit 0ec197e](https://github.com/IBM/nodejs-itoolkit/commit/0ec197e37114c34857eb75edf4b86889c0fdfdd7).
> [package.json] Bump version to 1.0.0-alpha.1

- lib/ixml.js
- test/unit/ixmlUnit.js
These test cases will help prevent regressions when refactoring `ixml.js`.
For example PR #52.
> [ixml.js] Add unit tests

- lib/SqlCall.js
- test/unit/SqlCallUnit.js
Found cases where calling SqlCall functions lead to type errors.
Solved these issues by ensuring options object parameter was indeed an object.
Before adding checks:
calling `SqlCall.setOptions()` without options object would throw  TypeError: Cannot convert undefined or null to object
calling `SqlCall.count()` without options object would throw TypeError: Cannot read property 'desc' of undefined
calling `SqlCall.describe()` without options object would throw TypeError: Cannot read property 'desc' of undefined
Added more unit tests using the different signatures of the test cases.
Tested cases where options object was passed and others where it was
not.
> [SqlCall.js] Add checks to ensure options is an object

- lib/ixml.js
First steps in simplifying [ixml.js](https://github.com/IBM/nodejs-itoolkit/blob/v1.0-dev/lib/ixml.js) file.
Removed all constants and replaced with string literals instead.
The remaining functions could be further simplified, most likely in a later PR.
Removed all constants and replaced with string literals instead.
Part of the overall issue #46.
> Start to simplify ixml.js

- CHANGELOG.md
- package.json
This PR adds a CHANGELOG.md  Resolves #84 
This PR also adds [standard-version](https://github.com/conventional-changelog/standard-version) which simplifies releasing a new version. 
Just run  `npm run release`. Resolves #85 
Using `standard-version` to automate change log generation our commits would need to follow the [Conventional Commits Spec](https://www.conventionalcommits.org/en/v1.0.0/#summary).
I suggest adding a bot like the following to our repo:  https://github.com/apps/semantic-pull-requests
> Add CHANGELOG

- lib/transports/irest.js
encodeURI() does not encode &, #, or ? characters, so if they are
present anywhere in the submitted XML document, they will cause the URI
to be invalid and result in a 400 error. Instead, using
encodeURIComponent() on each individual URL param will safely encode all
possible characters.
Thanks to @amagid for the original PR.
Obsoletes #72
Fixes #71
Co-authored-by: Aaron Magid <ahm64@case.edu>
> fix: Use encodeURIComponent for URL params

- lib/SqlCall.js
- lib/ixml.js
- test/unit/SqlCallUnit.js
> refactor: Remove ixml refs in SqlCall

- lib/CommandCall.js
- lib/ixml.js
> refactor: Remove ixml refs in CommandCall

- lib/Deprecated.js
- lib/ProgramCall.js
- lib/ixml.js
> refactor: Remove ixml refs in ProgramCall

- .gitignore
- package-lock.json
- package.json
A couple packages specified exact versions and those were changed to
allow minor version upgrades.
Based on some research it seems best practice is to commit the
package-lock.json. This is required for use by `npm ci` command, which
is in the default GitHub Actions workflow for npm packages.
Fixes #145
> build: Update dep vers and add package-lock.json

- .github/workflows/ci.yml
- package.json
The default GitHub Actions workflow for npm packages runs `npm test` and
while we could change this, I think it would be good to just have a
straightforward way to run unit tests. To run integration tests, there
is now a script, eg. `npm run test-integration`.
In the future, we could build a script runner such that you could say
run `npm test`, `npm test unit`, `npm test integration`, etc...
Fixes #144
> build: Add CI workflow and default to unit tests

- README.md
Main README still references SqlCall.
https://github.com/IBM/nodejs-itoolkit#sqlcall
We renamed it back to iSql and deprecated its use in v1.0.0 #119.
We now recommend using odbc, idb-connector, or idb-pconnector npm packages instead.
We still provide SqlCall examples in deprecated section of the [docs](https://github.com/IBM/nodejs-itoolkit/tree/master/docs#iSql)
Part of #95
> docs: Remove SqlCall example from main README

- lib/Deprecated.js
- lib/ProgramCall.js
- test/unit/ProgamCallUnit.js
> refactor: ProgramCall.addParam to accept an object

- lib/Toolkit.js
The bytes available and bytes provided fields were flipped around, which
is easy to do when they are not given names so names were also added.
Fixes #191
> fix: Define errno structure correctly

- test/functional/ProgramCallFunctional.js
> test: Pass object to addParam in ProgramCallFunctional.js

- test/functional/CommandCallFunctional.js
- test/functional/ProgramCallFunctional.js
- test/functional/ToolkitFunctional.js
- test/functional/checkObjectExists.js
- test/functional/config.js
- test/functional/deprecated/commandsFunctional.js
- test/functional/deprecated/iDataQueueFunctional.js
- test/functional/deprecated/iNetworkFunctional.js
- test/functional/deprecated/iObjFunctional.js
- test/functional/deprecated/iPgmFunctional.js
- test/functional/deprecated/iProdFunctional.js
- test/functional/deprecated/iSqlFunctional.js
- test/functional/deprecated/iUserSpaceFunctional.js
- test/functional/deprecated/iWorkFunctional.js
- test/functional/iSqlFunctional.js
Currently every transport is used to run each functional test.
This PR refactors to use only one transport per test case.
Also allows user to export `TKTRANSPORT` env variable to specify which transport to use.
Resolves #153
> test: Allow user to specify which transport to use

- lib/Deprecated.js
- lib/ProgramCall.js
- test/unit/ProgamCallUnit.js
> feat: Add Support for DS within return node

- lib/Connection.js
- lib/Deprecated.js
In v1, iConn is now a wrapper around Connection, however the
compatibility code was added to the Connection constructor instead of
having iConn do that, which means that Connection still had the same
signature as iConn and users could still use it the same way (though it
was not going to be documented as such). Instead, iConn should handle
its own compatibilty layer itself so that when the deprecated function
is removed, the compatibility layer is removed as well and it prevents
users from using Connection in a way that is not supported.
Fixes #221
> fix: Move iConn compatibility code to iConn itself

- lib/transports/idbTransport.js
By wrapping the user-specified callback in our own cleanup callback, we
can ensure that no matter how we called the callback, cleanup is always
done.
I also noticed some missing returns. Without these, we could continue
processing after the callback returns.
> fix(idb): Improve cleanup handling

- package-lock.json
- package.json
Fixes #202 
```
$ npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint [dev]                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ eslint > file-entry-cache > flat-cache > write > mkdirp >    │
│               │ minimist …
```
> fix: minimist CVE

- lib/istoredp.js
Deleting the statement object doesn't free the underlying resources,
causing memory leaks. Instead, we need to close both the connection and
the statement to free these resources. We can let the runtime delete the
objects as well.
Fixes #230
> fix: Properly close stmt and conn when using idb

- test/README.md
> docs: Update test/README.md

- lib/ProgramCall.js
> docs: Update jsdoc for ProgramCall.js

- .eslintrc.js
- lib/transports/idbTransport.js
- lib/transports/sshTransport.js
- package.json
- test/functional/checkObjectExists.js
- test/functional/deprecated/iProdFunctional.js
- test/functional/iDataQueueFunctional.js
> fix: eslint errors

- lib/Connection.js
- lib/Deprecated.js
- lib/transports/httpTransport.js
- test/README.md
- test/functional/config.js
> fix: HTTP transport should take a URL

- lib/CommandCall.js
- lib/Deprecated.js
We will be using sphinx-js for our documentation. Using \`\` \`\` to quote default values and valid options uses  [verbatim mode](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#text-formatting). This adds some formatting rather than simply quoting the values.
VS
> docs: fixup default value / valid options formatting

- README.md
> docs: Simplify main README to contain basic info

- docs/ProgramCall.rst
- docs/examples/cosine.js
Resolves #181
https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/rtref/trigono.htm
> docs: Add cosine.js for addReturn() example

- lib/transports/sshTransport.js
- test/functional/checkObjectExists.js
Fixes #270
[socket.destroy](https://nodejs.org/docs/latest/api/net.html#net_socket_destroy_error) Destroys the stream and closes the connection whereas [socket.end](https://nodejs.org/docs/latest/api/net.html#net_socket_end_data_encoding_callback) Half-closes the socket. i.e., it sends a FIN packet. 
Also see https://github.com/mscdex/ssh2/blob/master/lib/client.js#L713 and https://github.com/mscdex/ssh2/blob/master/lib/client.js#L704
> fix: ssh transport econnreset

- package-lock.json
- package.json
Bump version to `1.0.0-rc.1` to publish rc1 tag to npm. See https://github.com/IBM/nodejs-itoolkit/issues/275#issuecomment-622499158
> chore: Update version to 1.0.0-rc.1

- README.md
The example was missing `  });` at the end which causes: `SyntaxError: Unexpected end of input`
> fix: Missing braces in README Example

- lib/transports/sshTransport.js
Fix typo in error message mentioned in #285
> fix: Typo in ssh transport error message

- test/functional/ProgramCallFunctional.js
- test/functional/deprecated/iPgmFunctional.js
> test: Remove redundant ProgramCall test

- .eslintrc.js
- test/functional/CommandCallFunctional.js
- test/functional/ProgramCallFunctional.js
- test/functional/deprecated/commandsFunctional.js
- test/functional/deprecated/iDataQueueFunctional.js
- test/functional/deprecated/iNetworkFunctional.js
- test/functional/deprecated/iObjFunctional.js
- test/functional/deprecated/iPgmFunctional.js
- test/functional/deprecated/iProdFunctional.js
- test/functional/deprecated/iSqlFunctional.js
- test/functional/deprecated/iUserSpaceFunctional.js
- test/functional/deprecated/iWorkFunctional.js
- test/functional/iDataQueueFunctional.js
- test/functional/iNetworkFunctional.js
- test/functional/iObjFunctional.js
- test/functional/iProdFunctional.js
- test/functional/iSqlFunctional.js
- test/functional/iUserSpaceFunctional.js
- test/functional/iWorkFunctional.js
- test/unit/CommandCallUnit.js
- test/unit/ConnectionUnit.js
- test/unit/ProgamCallUnit.js
- test/unit/deprecated/commandsUnit.js
- test/unit/deprecated/iConnUnit.js
- test/unit/deprecated/iPgmUnit.js
- test/unit/deprecated/iSqlUnit.js
- test/unit/deprecated/xmlToJsonUnit.js
> test: Remove arrow functions from mocha functions

- .github/workflows/ci.yml
Resolves #201 
Workflow added from https://github.com/hallee/eslint-action#usage
> ci: Add eslint action

- test/README.md
> docs: Update setup transport interface links

- .github/workflows/stale.yml
These labels are plural since v2 to support multiple exempt labels, but
this broke the current setup as the old singular exempt options are no
longer accepted.
> fix: Make exempt labels plural for stale action

- test/functional/CommandCallFunctional.js
- test/functional/checkVersion.js
- test/functional/deprecated/commandsFunctional.js
> test: Check the XMLSERVICE version for QSH support

- package-lock.json
- package.json
Resolved by running 
```bash
$ npm audit fix --force 
```
Force was used because standard-version was bumped from 8.x.x --> 9.x.x.
> fix: Update standard-version to resolve CVE-2020-8116

- .eslintrc.js
- lib/transports/httpTransport.js
- lib/transports/idbTransport.js
- lib/transports/odbcTransport.js
- lib/transports/sshTransport.js
> refactor: Handle optional dependencies better

- .eslintrc.js
- test/functional/ProgramCallFunctional.js
- test/functional/deprecated/iPgmFunctional.js
> test: Fix mocha/no-identical-title eslint issue

- .eslintrc.js
- test/functional/deprecated/iWorkFunctional.js
- test/functional/iWorkFunctional.js
Part of #289
Removed the `before hook` and moved the hooks' operations in the test directly.
See https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-hooks-for-single-case.md
> test: Fix mocha/no-hooks-for-single-case eslint issue

- .eslintrc.js
Our project uses optional deps like odbc and idb-connector packages.
Here we disabled the import/no-unresolved rule in our .eslint.js file.
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md
Fixes #335
> fix: eslint GH action failure

- docs/Connection.rst
Added a comma to separate the properties in transportOptions object.
> docs: Add comma to separate password and url key

- lib/Connection.js
- lib/Deprecated.js
- lib/transports/idbTransport.js
- lib/transports/odbcTransport.js
- package-lock.json
- package.json
- test/functional/CommandCallFunctional.js
- test/functional/ProgramCallFunctional.js
- test/functional/checkObjectExists.js
- test/functional/deprecated/iUserSpaceFunctional.js
- test/functional/deprecated/iWorkFunctional.js
- test/functional/iNetworkFunctional.js
- test/functional/iUserSpaceFunctional.js
- test/unit/ConnectionUnit.js
- test/unit/ProgamCallUnit.js
- test/unit/deprecated/iConnUnit.js
- test/unit/deprecated/iPgmUnit.js
- test/unit/deprecated/xmlToJsonUnit.js
- Drop standard-version as it is now deprecated
- Update mocha binaray name in test scripts
After these changes running npm audit returns:
```
$ npm audit
ssh2  <1.4.0
Severity: high
OS Command Injection in ssh2 - https://github.com/advisories/GHSA-652h-xwhf-q4h6
fix available via `npm audit fix --force`
Will install ssh2@1.11.0, which is a breaking change
node_modules/ssh2
1 high severity vulnerability
To address all issues (including breaking changes), run:
npm audit fix --force
```
Still need to investigate possible breaking changes in ssh2 1.x.x in #338
> build(deps): Updated deps to the latest version

- README.md
- docs/examples/cosine.js
- docs/examples/qusrobjd.js
- docs/examples/rtvjoba.js
- docs/migratation-guide-v1.0.rst
- lib/Deprecated.js
This PR updates documentation, documentation code samples, and the `xmlToJson` deprecation message to suggest the use of `fast-xml-parser` over `xml2js`. 
Previous issues, confusion, and lack of maintenance of `xml2js` outlined in #344 lead to this PR.
> Docs: Reference alternate XML parser

- package.json
Add `fast-xml-parser` as an optional dependency now that we recommend it.
See https://github.com/IBM/nodejs-itoolkit/issues/344#issuecomment-1286319878
> build(deps): Add fast-xml-parser

- package-lock.json
- package.json
Previously we relied on 0.8.x this a major version upgrade.
Versions of ssh2 <1.4.0 are vulnerable to OS Command injection on Windows.
See https://github.com/advisories/GHSA-652h-xwhf-q4h6
Functional tests passed with latest ssh2 on both Linux and IBM i.
> build(deps): Upgrade ssh2 to latest version

- lib/transports/idbTransport.js
- lib/transports/odbcTransport.js
odbc and idb-connector are optional deps and might not be installed.
When either is not available, return an error back to user instead of failing.
Fixes #317
> fix: Better optional deps handling

- .github/workflows/publish.yml
Added from
https://github.com/actions/starter-workflows/blob/9bca5754a6e9b132c49c1715085c747b21278dc9/ci/npm-publish.yml#L4
Fixes #357
> ci: Add npm publish action

- docs/examples/cosine.js
This C library function, cos(), assumes pass by value, whereas XMLSERVICE defaults to pass-by-reference. If we don't specify "pass by value," we can get incorrect results, because we will be sending a pointer rather than a value. (Pass radian value 3.1459 to test.)
Signed-off-by: Alan Seiden <alan@alanseiden.com>
> docs: Update cosine example to pass by value

- .github/workflows/ci.yml
Fixes #352
Currently we don't have a remote system to run the integration tests on. This causes every PR check to fail. Until we resolve this disable running the integration tests.
- Mocha.js 10.x.x supports min node 14 so update the node version matrix to node 14, 16, 18.
- Bump setup-node and checkout actions to the latest version
> ci: Disable running integration tests

- docs/Connection.rst
The guide link was pointing to the GitHub page with the link to the actual docs page. Adding direct link instead. https://ibmi-oss-docs.readthedocs.io/en/latest/odbc/README.html
> Added correct link

- .github/workflows/publish.yml
- .gitignore
- .release-it.json
- README.md
- docs/RELEASE.md
- package-lock.json
- package.json
For more details on the release process, please read docs/RELEASE.md
Now we restrict the files packaged using the files section of the package.json
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files
> ci: update release process

- .readthedocs.yml
The build.os attribute is now required and configs without it will fail to build starting on October 16. See
https://blog.readthedocs.com/use-build-os-config/
Also migrate Python version from python.version to build.tools.python as the former is also deprecated.
> docs: Remove deprecated attributes from RtD config

- test/functional/CommandCallFunctional.js
- test/functional/ProgramCallFunctional.js
- test/functional/deprecated/commandsFunctional.js
- test/functional/deprecated/iPgmFunctional.js
- test/functional/deprecated/iSqlFunctional.js
- test/functional/iSqlFunctional.js
After adding changes to replace xml2js, there were some lint errors this PR fixes the errors
> test: fix eslint errors
