IBM/nodejs-itoolkit

- lib/itoolkit.js
- lib/ixml.js
- test/unit/iPgmUnit.js
Fix to allow service programs with parameters defined with "value" to work.
> Pass by value

- README.md
- test/README.md
Update the main README to reflect the current API.
Also update test/README to show how to configure tests
> Update README with v1.0.0 changes

- README.md
- package.json
- [README.md] Update install docs for alpha version
- [package.json] Bump version to 1.0.0-alpha.0
[Reference](https://medium.com/@kevinkreuzer/publishing-a-beta-or-alpha-version-to-npm-46035b630dd7) to release alpha/beta versions.
> Prepare to release 1.0.0-alpha

- lib/SqlCall.js
- test/unit/ixmlUnit.js
> [SqlCall.js] Remove .connect and .setOptions #56

- .github/workflows/semantic-pull-requests.yml
See https://www.conventionalcommits.org/en/v1.0.0/
Follow-on to #86
> ci: Add PR title linter following conventional commits

- .github/workflows/stale.yml
> ci: Add stale action

- test/unit/SqlCallUnit.js
> test: Remove unused SqlCallUnit tests

- lib/Connection.js
- lib/ixml.js
> refactor: Remove ixml refs in Connection

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> ci: Add issue templates

- .github/ISSUE_TEMPLATE/bug_report.md
> fix: Formatting errors in bug report template

- lib/Connection.js
- lib/transports/httpTransport.js
- lib/transports/idbTransport.js
> refactor: Rename irest and istoredp transports

- lib/Deprecated.js
- test/unit/deprecated/iSqlUnit.js
> refactor: Disable use of .connect and .setOptions in iSql

- lib/Connection.js
> fix: Add missing '?' in xml prolog

- package.json
> build: Add xml2js as a dependency

- lib/ProgramCall.js
> fix: Faulty error thrown by ProgramCall.addParam

- docs/README.md
> docs: Remove SqlCall

- test/functional/CommandCallFunctional.js
- test/functional/deprecated/commandsFunctional.js
> refactor: Remove xmlToJson from command tests

- test/functional/ProgramCallFunctional.js
- test/functional/deprecated/iPgmFunctional.js
> refactor: Remove xmlToJson from program tests

- test/functional/deprecated/iSqlFunctional.js
- test/functional/iSqlFunctional.js
> refactor: Remove xmlToJson from iSql tests

- lib/Toolkit.js
> refactor: Remove xmlToJson from Toolkit data queue methods

- lib/Toolkit.js
> refactor: Remove xmlToJson from Toolkit network methods

- lib/Toolkit.js
> refactor: Remove xmlToJson from Toolkit object methods

- lib/Toolkit.js
> refactor: Remove xmlToJson from Toolkit product methods

- lib/Toolkit.js
> refactor: Remove xmlToJson from Toolkit user space methods

- lib/Toolkit.js
> refactor: Remove xmlToJson from Toolkit work methods

- README.md
- docs/README.md
> docs: Replace xmlToJson with xml2js in example code

- docs/README.md
> docs: Move xmlToJson to deprecated section

- README.md
> docs: Update Apache setup in main README

- README.md
> docs: Link to odbc setup guide for odbc transport

- lib/Toolkit.js
> refactor: Pass object to addParam in iDataQueue functions

- lib/Toolkit.js
> refactor: Pass object to addParam in iUserSpace functions

- lib/Toolkit.js
> refactor: Pass object to addParam in iProd functions

- lib/Toolkit.js
> refactor: Pass object to addParam in iObj functions

- lib/Toolkit.js
> refactor: Pass object to addParam in iNetwork functions

- lib/Toolkit.js
> refactor: Pass object to addParam in iWork functions

- lib/Toolkit.js
> fix: data type issue in Toolkit.getSysStatus and Toolkit.getSysStatusExt

- lib/ProgramCall.js
> refactor: Remove unsupported data and ds options

- README.md
> docs: Remove Toolkit example from main README

- lib/Deprecated.js
> refactor!: Remove unused functions

- test/unit/ProgamCallUnit.js
> test: Adding a nested DS

- package.json
Update the version to 0.1.7 before making a new release.
https://github.com/IBM/nodejs-itoolkit/pull/232#issuecomment-611580747
> chore: Update version to 0.1.7

- lib/transports/sshTransport.js
> fix: ssh transport silent failure

- lib/CommandCall.js
> docs: Update jsdoc for CommandCall.js

- lib/Connection.js
> docs: Update jsdoc for Connection.js

- lib/Deprecated.js
- test/functional/deprecated/iNetworkFunctional.js
- test/functional/deprecated/iObjFunctional.js
- test/functional/deprecated/iProdFunctional.js
- test/functional/iNetworkFunctional.js
- test/functional/iObjFunctional.js
- test/functional/iProdFunctional.js
- test/functional/iWorkFunctional.js
> fix: TODOs in Deprecated.js

- lib/Deprecated.js
> docs: Update jsdoc for Deprecated.js

- README.md
> docs: Update doc link to point at readthedocs

- README.md
> docs: Add/Update badges

- test/functional/deprecated/commandsFunctional.js
- test/functional/deprecated/iDataQueueFunctional.js
- test/functional/deprecated/iNetworkFunctional.js
- test/functional/deprecated/iObjFunctional.js
- test/functional/deprecated/iPgmFunctional.js
- test/functional/deprecated/iProdFunctional.js
- test/functional/deprecated/iSqlFunctional.js
- test/functional/deprecated/iUserSpaceFunctional.js
- test/functional/deprecated/iWorkFunctional.js
> fix: Deprecated functional tests rest transport options

- test/functional/checkObjectExists.js
> fix: Test hooks timeout when using rest transport

- package.json
> fix: Homepage link in package.json

- docs/Connection.rst
After #252 the example needed an update.
> docs: Update creating a connection using rest transport example

- lib/Deprecated.js
> fix: iConn unit test failure

- .github/workflows/stale.yml
> ci: Add exempt-pr-label to stale action

- .npmignore
> chore: NPM ignore docs dir

- package-lock.json
- package.json
> chore: Update version to 1.0.0

- lib/Deprecated.js
> fix: Emit deprecation warning for iPgm.addReturn

- docs/requirements.txt
> build: fix readthedocs build error

- package.json
Shortcut helper script to run lint fixes.
```bash
npm run lint-fix
```
While in proximity remove obsolete release script
> build(package.json): Add lint-fix script
